### ISSUE TITLE
me agregas?'

### ISSUE THREAD

**Issue by gabrielamg24** [edisagarcia/PCfB#1]
=))

**Comment by edisagarcia** [comment]
Yep!

**Comment by gabrielamg24** [comment]
quieres solicitarme que te agregue y te rechazo? es uno de los pasos
quetenemos que hacer

2017-01-20 11:17 GMT+01:00 edisagarcia <notifications@github.com>:

**Comment by edisagarcia** [comment]
te mande una issue
